In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.ensemble

In [37]:
#import sklearn.linear_model

In [38]:
data=pd.read_csv('Iris.csv')

In [39]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [40]:
y=data['Species']

In [41]:
data=data.drop(['Id','Species'],axis=1)

In [42]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [43]:
x=data

In [44]:
x.shape

(150, 4)

In [45]:
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)

In [46]:
clf=sklearn.ensemble.RandomForestClassifier(random_state=0)

In [47]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [48]:
clf.score(x_test,y_test)

0.9666666666666667

In [49]:
clf.feature_importances_

array([0.14234692, 0.03619971, 0.4001239 , 0.42132948])

In [81]:
data=pd.read_csv('traintitanic.csv')

In [82]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [83]:
data=data.drop(["PassengerId","Fare","Ticket","Name","Cabin"],axis=1)

In [84]:
data=data.join(pd.get_dummies(data['Sex']))

In [85]:
data=data.drop(["Sex"],axis=1)
data=data.join(pd.get_dummies(data['Embarked']))
data=data.drop(["Embarked"],axis=1)

In [86]:
data=data.drop(['female'],axis=1)

In [87]:
data.shape

(891, 9)

In [88]:
data=data.dropna()
y=data["Survived"]
x=data.drop(['Survived'],axis=1)

In [89]:
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)

In [90]:
clf=sklearn.ensemble.RandomForestClassifier(random_state=0)

In [91]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [92]:
clf.score(x_test,y_test)

0.7972027972027972

In [95]:
x

Pclass   Age  SibSp  Parch  male  C  Q  S
0         3  22.0      1      0     1  0  0  1
1         1  38.0      1      0     0  1  0  0
2         3  26.0      0      0     0  0  0  1
3         1  35.0      1      0     0  0  0  1
4         3  35.0      0      0     1  0  0  1
6         1  54.0      0      0     1  0  0  1
7         3   2.0      3      1     1  0  0  1
8         3  27.0      0      2     0  0  0  1
9         2  14.0      1      0     0  1  0  0
10        3   4.0      1      1     0  0  0  1
11        1  58.0      0      0     0  0  0  1
12        3  20.0      0      0     1  0  0  1
13        3  39.0      1      5     1  0  0  1
14        3  14.0      0      0     0  0  0  1
15        2  55.0      0      0     0  0  0  1
16        3   2.0      4      1     1  0  1  0
18        3  31.0      1      0     0  0  0  1
20        2  35.0      0      0     1  0  0  1
21        2  34.0      0      0     1  0  0  1
22        3  15.0      0      0     0  0  1  0
23        1  28.0      0      0     1  0  0  1
24        3   8.0      3      1     0  0  0  1
25        3  38.0      1      5     0  0  0  1
27        1  19.0      3      2     1  0  0  1
30        1  40.0      0      0     1  1  0  0
33        2  66.0      0      0     1  0  0  1
34        1  28.0      1      0     1  1  0  0
35        1  42.0      1      0     1  0  0  1
37        3  21.0      0      0     1  0  0  1
38        3  18.0      2      0     0  0  0  1
..      ...   ...    ...    ...   ... .. .. ..
856       1  45.0      1      1     0  0  0  1
857       1  51.0      0      0     1  0  0  1
858       3  24.0      0      3     0  1  0  0
860       3  41.0      2      0     1  0  0  1
861       2  21.0      1      0     1  0  0  1
862       1  48.0      0      0     0  0  0  1
864       2  24.0      0      0     1  0  0  1
865       2  42.0      0      0     0  0  0  1
866       2  27.0      1      0     0  1  0  0
867       1  31.0      0      0     1  0  0  1
869       3   4.0      1      1     1  0  0  1
870       3  26.0      0      0     1  0  0  1
871       1  47.0      1      1     0  0  0  1
872       1  33.0      0      0     1  0  0  1
873       3  47.0      0      0     1  0  0  1
874       2  28.0      1      0     0  1  0  0
875       3  15.0      0      0     0  1  0  0
876       3  20.0      0      0     1  0  0  1
877       3  19.0      0      0     1  0  0  1
879       1  56.0      0      1     0  1  0  0
880       2  25.0      0      1     0  0  0  1
881       3  33.0      0      0     1  0  0  1
882       3  22.0      0      0     0  0  0  1
883       2  28.0      0      0     1  0  0  1
884       3  25.0      0      0     1  0  0  1
885       3  39.0      0      5     0  0  1  0
886       2  27.0      0      0     1  0  0  1
887       1  19.0      0      0     0  0  0  1
889       1  26.0      0      0     1  1  0  0
890       3  32.0      0      0     1  0  1  0

[714 rows x 8 columns]

In [96]:
clf.feature_importances_ #Age is most import

array([0.13144422, 0.44550763, 0.06816673, 0.06391543, 0.25122221,
       0.01723423, 0.00431621, 0.01819333])

In [123]:
boston = sklearn.datasets.load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [124]:
feature=boston.feature_names
feature

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [125]:
data=boston.data

In [126]:
x=data

In [127]:
y=boston.target

In [128]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [129]:
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)

In [130]:
clf=sklearn.ensemble.RandomForestRegressor(random_state=0)

In [131]:
clf.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [137]:
clf.score(x_test,y_test)

0.8865680927245053

In [138]:
clf.feature_importances_

array([0.03196131, 0.00080265, 0.00552057, 0.00052029, 0.01210249,
       0.39764025, 0.0111302 , 0.0855399 , 0.00431689, 0.01747825,
       0.02033082, 0.01072538, 0.40193099])